'use client';
import {useEffect,useState} from 'react';
const seed={routers:[],packages:[{id:1,name:'Masaa 12',validity:'12 Hours',price:500},{id:2,name:'Siku',validity:'1 Day',price:1000},{id:3,name:'Week',validity:'7 Days',price:5000},{id:4,name:'Mwezi',validity:'30 Days',price:15000}],vouchers:[],sales:[],payments:[],sites:[],tenants:[]};
const nav=[['dashboard','▦','Dashboard'],['routers','📡','MikroTik Routers'],['packages','▤','Voucher Packages'],['vouchers','🎟','Vouchers'],['sales','💰','Sales'],['payments','💳','Payments'],['sites','▦','Sites'],['tenants','👥','Tenants']];
function money(n){return new Intl.NumberFormat('en-TZ').format(n||0)+' TSh'}
export default function Page(){
 const [logged,setLogged]=useState(false),[page,setPage]=useState('dashboard'),[data,setData]=useState(seed),[login,setLogin]=useState({u:'',p:''}),[toast,setToast]=useState('');
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('markazwifi'));if(x)setData(x);if(localStorage.getItem('markazwifi_auth')==='1')setLogged(true)}catch{}},[]);
 useEffect(()=>{localStorage.setItem('markazwifi',JSON.stringify(data))},[data]);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 if(!logged)return <Login login={login} setLogin={setLogin} onLogin={()=>{if(login.u==='admin'&&login.p==='MarkazwifiBismillah'){localStorage.setItem('markazwifi_auth','1');setLogged(true)}else notify('Username au password si sahihi')}} toast={toast}/>;
 const counts={routers:data.routers.length,packages:data.packages.length,vouchers:data.vouchers.length,sales:data.sales.length,payments:data.payments.length,sites:data.sites.length,tenants:data.tenants.length};
 return <div className="shell"><aside><div className="brand">MARKAZ WIFI</div><div className="subbrand">Bismillah • Control Center</div><nav>{nav.map(([id,ic,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><span>{ic}</span>{label}</button>)}</nav><button className="logout" onClick={()=>{localStorage.removeItem('markazwifi_auth');setLogged(false)}}>↪ Logout</button></aside><main><header><div><h1>{nav.find(x=>x[0]===page)?.[2]||'Dashboard'}</h1><p>MARKAZ WIFI • Multi-Tenant Hotspot & Billing</p></div><div className="status"><i/> System Ready</div></header>{page==='dashboard'?<Dashboard data={data} counts={counts} setPage={setPage}/>:<Module page={page} data={data} setData={setData} notify={notify}/>} {toast&&<div className="toast">{toast}</div>}</main></div>
}
function Login({login,setLogin,onLogin,toast}){return <div className="loginWrap"><div className="loginCard"><div className="loginLogo"><div className="wifi">⌁</div><b>MARKAZ <em>WIFI</em></b></div><h2>Karibu MARKAZ WIFI</h2><p>Admin Control Panel</p><input placeholder="Username" value={login.u} onChange={e=>setLogin({...login,u:e.target.value})}/><input type="password" placeholder="Password" value={login.p} onChange={e=>setLogin({...login,p:e.target.value})}/><button className="primary" onClick={onLogin}>Login</button><small>Admin access • Fresh installation</small>{toast&&<div className="error">{toast}</div>}</div></div>}
function Dashboard({data,counts,setPage}){let total=data.sales.reduce((a,x)=>a+x.amount,0);return <section><div className="hero"><div><span className="pill">READY</span><h2>MARKAZ WIFI Dashboard</h2><p>Simamia routers, vouchers, mauzo, malipo na tenants kutoka sehemu moja.</p></div><button className="primary" onClick={()=>setPage('vouchers')}>+ Create Voucher</button></div><div className="stats">{[['routers','📡','Routers'],['packages','▤','Packages'],['vouchers','🎟','Vouchers'],['sales','💰','Sales'],['payments','💳','Payments'],['tenants','👥','Tenants']].map(x=><div className="stat" key={x[0]}><span>{x[1]}</span><div><b>{counts[x[0]]}</b><small>{x[2]}</small></div></div>)}</div><div className="grid2"><div className="panel"><h3>Sales Overview</h3><div className="big">{money(total)}</div><p>Total recorded sales</p><div className="empty">{data.sales.length?'Sales data available':'No sales yet — create your first voucher.'}</div></div><div className="panel"><h3>System Status</h3><Row k="Database" v="Ready" ok/><Row k="Voucher Engine" v="Ready" ok/><Row k="MikroTik API" v="Waiting for router"/><Row k="Payments" v="Ready for configuration"/></div></div></section>}
function Row({k,v,ok}){return <div className="row"><span>{k}</span><b className={ok?'green':''}>{v}</b></div>}
function Module({page,data,setData,notify}){const title=nav.find(x=>x[0]===page)?.[2];const key=page;const arr=data[key]||[];const [name,setName]=useState('');const [price,setPrice]=useState('');const [validity,setValidity]=useState('');
 const add=()=>{if(page==='packages'){if(!name||!price||!validity)return notify('Jaza jina, bei na validity');setData({...data,packages:[...data.packages,{id:Date.now(),name,price:Number(price),validity}]});notify('Package imeongezwa')} else if(page==='vouchers'){const pkg=data.packages.find(p=>p.id===Number(validity))||data.packages[0];if(!pkg)return notify('Tengeneza package kwanza');const code='MKZ-'+Math.random().toString(36).slice(2,8).toUpperCase();setData({...data,vouchers:[...data.vouchers,{id:Date.now(),code,package:pkg.name,price:pkg.price,status:'Unused'}]});notify('Voucher imeundwa')} else {if(!name)return notify('Jaza jina');setData({...data,[key]:[...arr,{id:Date.now(),name,price:page==='payments'?Number(price||0):undefined,status:'Ready'}]});notify(title+' imeongezwa') }setName('');setPrice('');setValidity('')};
 return <section><div className="panel formPanel"><h2>{title}</h2><p>Module mpya ya MARKAZ WIFI. Hakuna data ya mfumo wa zamani.</p><div className="formgrid"><input placeholder={page==='routers'?'Router name':'Name'} value={name} onChange={e=>setName(e.target.value)}/>{page==='packages'&&<><input placeholder="Price (TSh)" type="number" value={price} onChange={e=>setPrice(e.target.value)}/><input placeholder="Validity e.g. 12 Hours" value={validity} onChange={e=>setValidity(e.target.value)}/></>}{page==='vouchers'&&<select value={validity} onChange={e=>setValidity(e.target.value)}><option value="">Select package</option>{data.packages.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.price)}</option>)}</select>}{page==='payments'&&<input placeholder="Amount (TSh)" type="number" value={price} onChange={e=>setPrice(e.target.value)}/>}<button className="primary" onClick={add}>+ Add</button></div></div><div className="panel"><div className="tableHead"><h3>{title} List</h3><span>{arr.length} records</span></div>{arr.length===0?<div className="empty">Hakuna records bado.</div>:<div className="table">{arr.map(x=><div className="tr" key={x.id}><b>{x.code||x.name}</b><span>{x.package||x.validity|| (x.price?money(x.price):'')}</span><span className="green">{x.status||'Ready'}</span></div>)}</div>}</div></section>}
